version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.Web.Api/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "Smalls1652"
    target-branch: "main"
